name: ArchaicCore
version: '1.0-SNAPSHOT'
main: me.b77.archaiccore.ArchaicCore
authors: [ B77 ]
description: A plugin required for Archaic Network
commands:
  archaic:
    description: Main command for ArchaicCore
    aliases:
      - ar

